# WebScrapping

In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [2]:
url = "https://companiesmarketcap.com/largest-companies-by-revenue/"

page = requests.get(url)
soup = BeautifulSoup(page.text, 'html.parser')

#<table class="default-table table marketcap-table dataTable" style="width:100%">

In [3]:
print(soup)

<!DOCTYPE html>

<html lang="en-US">
<head>
<title>Companies ranked by revenue - CompaniesMarketCap.com</title>
<meta charset="utf-8"/>
<link href="https://companiesmarketcap.com/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="/img/icons/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="/img/icons/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="/img/icons/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="/img/icons/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="/img/icons/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="/img/icons/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="/img/icons/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="/img/icons/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="/img/icons/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="/img/icons/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="/img/icons/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="/img/icons/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>
<link href="/img/icons/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="/img/icons/manifest.json" rel="manifest"/>
<link href="https://companiesmarketcap.com/de/groesste-unternehmen-nach-umsatz/" hreflang="de" rel="alternate">
<link href="https://companiesmarketcap.com/fr/plus-grandes-entreprises-par-chiffre-d-affaires/" hreflang="fr" rel="alternate">
<link href="https://companiesmarketcap.com/largest-companies-by-revenue/" hreflang="en-US" rel="alternate">
<link href="https://companiesmarketcap.com/eur/largest-companies-by-revenue/" hreflang="en-IE" rel="alternate">
<link href="https://companiesmarketcap.com/inr/largest-companies-by-revenue/" hreflang="en-IN" rel="alternate">
<link href="https://companiesmarketcap.com/gbp/largest-companies-by-revenue/" hreflang="en-GB" rel="alternate">
<link href="https://companiesmarketcap.com/cad/largest-companies-by-revenue/" hreflang="en-CA" rel="alternate">
<link href="https://companiesmarketcap.com/aud/largest-companies-by-revenue/" hreflang="en-AU" rel="alternate">
<link href="https://companiesmarketcap.com/nzd/largest-companies-by-revenue/" hreflang="en-NZ" rel="alternate">
<link href="https://companiesmarketcap.com/hkd/largest-companies-by-revenue/" hreflang="en-HK" rel="alternate">
<link href="https://companiesmarketcap.com/sgd/largest-companies-by-revenue/" hreflang="en-SG" rel="alternate">
<link href="https://companiesmarketcap.com/largest-companies-by-revenue/" rel="canonical">
<meta content="https://companiesmarketcap.com/largest-companies-by-revenue/" property="og:url"/>
<meta content="INDEX,FOLLOW" name="robots"/>
<meta content="#ffffff" name="msapplication-TileColor"/>
<meta content="/img/icons/ms-icon-144x144.png" name="msapplication-TileImage"/>
<meta content="#ffffff" name="theme-color"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="en-US" http-equiv="content-language"/>
<meta content="Companies ranked by revenue - CompaniesMarketCap.com" property="og:title"/><meta content="website" property="og:type">
<meta content="Ranking of the world's top publicly traded stock companies by revenue (TTM)" property="og:description"/>
<meta content="https://companiesmarketcap.com/logo.png" property="og:image"/>
<meta content="Ranking of the world's top publicly traded stock companies by revenue (TTM)" name="description"/>
<link href="/bt-replacement.css?v=9" rel="stylesheet" type="text/css"/>
<link href="/css/style.css?v=345" rel="stylesheet" type="text/css"/>
<script>
current_locale = "usd";
current_locale_path = "";

current_marketcap_path = "marketcap";
</script>
<script async="" src="https://cdn.fuseplatform.net/publift/tags/2/3432/fuse.js"></script></meta></link></link></link></link></link></link></link></link></link></link></link></link></head>
<body class="cmkt" id="cmkt">
<div class="row site-header-row">
<div class="site-header">
<span style="display: inline-flex; margin-top: 2px;">
<span class="max-width-720px-hidden">
                        Companies: <span class="font-weight-bold">10,652</span>
                        total market cap: <span class="font-weight-bold"><a class="total-mcap-link" href="/total-marketcap/">$140.500 T</a></span>
</span>
</span>
<div class="header-actions">
<a class="header-button sign-in-button sign-in" href="#">Sign In</a>
<div class="dropdown currency-dropdown">
<a aria-expanded="false" aria-haspopup="true" class="header-button dropdown-toggle" data-toggle="dropdown" href="#" id="languageDropdown">
                        🇺🇸 <span class="responsive-shown-inline">EN</span><span class="responsive-hidden">English</span> </a>
<div aria-labelledby="languageDropdown" class="dropdown-menu currency-menu">
<a class="dropdown-item" href="/de/groesste-unternehmen-nach-umsatz/" onclick="document.cookie = 'pref_language=DE;  max-age=91536000000; path=/;';">🇩🇪 Deutsch</a><a class="dropdown-item" href="/fr/plus-grandes-entreprises-par-chiffre-d-affaires/" onclick="document.cookie = 'pref_language=FR;  max-age=91536000000; path=/;';">🇫🇷 Français</a> </div>
</div>
<div class="dropdown currency-dropdown">
<a aria-expanded="false" aria-haspopup="true" class="header-button dropdown-toggle" data-toggle="dropdown" href="#" id="currencyDropdown">
                        $ USD                        </a>
<div aria-labelledby="currencyDropdown" class="dropdown-menu currency-menu">
<a class="dropdown-item" href="/eur/largest-companies-by-revenue/" onclick="document.cookie = 'pref_currency=EUR;  max-age=91536000000; path=/;';"><span class="symbol">€</span><span class="currency-code">EUR</span><span class="currency-flag">🇪🇺</span></a><a class="dropdown-item" href="/inr/largest-companies-by-revenue/" onclick="document.cookie = 'pref_currency=INR;  max-age=91536000000; path=/;';"><span class="symbol">₹</span><span class="currency-code">INR</span><span class="currency-flag">🇮🇳</span></a><a class="dropdown-item" href="/gbp/largest-companies-by-revenue/" onclick="document.cookie = 'pref_currency=GBP;  max-age=91536000000; path=/;';"><span class="symbol">£</span><span class="currency-code">GBP</span><span class="currency-flag">🇬🇧</span></a><a class="dropdown-item" href="/cad/largest-companies-by-revenue/" onclick="document.cookie = 'pref_currency=CAD;  max-age=91536000000; path=/;';"><span class="symbol">$</span><span class="currency-code">CAD</span><span class="currency-flag">🇨🇦</span></a><a class="dropdown-item" href="/aud/largest-companies-by-revenue/" onclick="document.cookie = 'pref_currency=AUD;  max-age=91536000000; path=/;';"><span class="symbol">$</span><span class="currency-code">AUD</span><span class="currency-flag">🇦🇺</span></a><a class="dropdown-item" href="/nzd/largest-companies-by-revenue/" onclick="document.cookie = 'pref_currency=NZD;  max-age=91536000000; path=/;';"><span class="symbol">$</span><span class="currency-code">NZD</span><span class="currency-flag">🇳🇿</span></a><a class="dropdown-item" href="/hkd/largest-companies-by-revenue/" onclick="document.cookie = 'pref_currency=HKD;  max-age=91536000000; path=/;';"><span class="symbol">$</span><span class="currency-code">HKD</span><span class="currency-flag">🇭🇰</span></a><a class="dropdown-item" href="/sgd/largest-companies-by-revenue/" onclick="document.cookie = 'pref_currency=SGD;  max-age=91536000000; path=/;';"><span class="symbol">$</span><span class="currency-code">SGD</span><span class="currency-flag">🇸🇬</span></a> </div>
</div>
<a class="dark-hidden" href="#" id="light-off-btn" title="change to dark mode">
<svg height="16" viewbox="0 70 1000 1000" width="16" xmlns="http://www.w3.org/2000/svg">
<path d="M525.3,989.5C241.2,989.5,10,758.3,10,474.1c0-196.8,109.6-373.6,285.9-461.4c7.9-3.9,17.5-2.4,23.7,3.8c6.2,6.2,7.9,15.8,4,23.7c-32.2,65.4-48.5,135.7-48.5,208.9c0,261.4,212.7,474.1,474.1,474.1c74,0,145-16.7,211-49.5c7.9-3.9,17.5-2.4,23.7,3.8c6.3,6.3,7.9,15.8,3.9,23.7C900.5,879,723.3,989.5,525.3,989.5z"></path>
</svg>
</a>
<a class="dark-shown" href="#" id="light-on-btn" title="change to light mode">
<svg height="16" viewbox="10 10 220 220" width="16" xmlns="http://www.w3.org/2000/svg">
<path d="M120,189.697c-38.492,0-69.696-31.205-69.696-69.697S81.508,50.303,120,50.303c38.494,0,69.699,31.205,69.699,69.697 S158.494,189.697,120,189.697z M203.975,140L240,120l-36.025-20V140z M36.025,100L0,120l36.025,20V100z M120,240l20-36.025h-40 L120,240z M120,0l-20,36.025h40L120,0z M46.481,165.238l-11.333,39.615l39.616-11.33L46.481,165.238z M165.238,46.477l28.283,28.285 l11.332-39.613L165.238,46.477z M35.148,35.148L46.48,74.762l28.283-28.285L35.148,35.148z M165.238,193.523l39.615,11.33 l-11.332-39.615L165.238,193.523z"></path>
</svg>
</a>
</div>
</div>
</div>
<nav class="navbar nav-bar-companiesmarketcap navbar-expand-lg navbar-light">
<div class="navbar-collapse-container">
<button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarSupportedContent" data-toggle="collapse" type="button">
<span class="navbar-toggler-icon"></span>
</button>
<form class="search-form form-inline">
<input aria-label="Company name, ticker..." autocomplete="off" class="form-control search-input" id="search-input" placeholder="Company name, ticker..." type="search"/>
<button class="btn-search" disabled="" onclick="return false;" type="submit"><svg height="18" viewbox="0 0 14 14" width="18" xmlns="http://www.w3.org/2000/svg"><g fill="none" stroke="#6c6c6c" stroke-width="2"><path d="M11.29 11.71l-4-4"></path><circle cx="5" cy="5" r="4"></circle></g></svg></button>
<div class="typeahead-search-results" id="typeahead-search-results"></div>
</form>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
<a class="responsive-hidden" href="/" title="CompaniesMarketCap.com - companies ranked by market capitalization">
<div class="companiesmarketcap-logo"></div>
</a>
<ul class="navbar-nav">
<li class="nav-item">
<a class="nav-link nav-link-companiesmarketcap" href="/">Global ranking</a>
</li>
<li class="nav-item dropdown megamenu-li">
<a aria-expanded="false" aria-haspopup="true" class="nav-link nav-link-companiesmarketcap dropdown-toggle" data-toggle="dropdown" href="#" id="dropdown-countries">Ranking by countries</a>
<div aria-labelledby="dropdown-countries" class="dropdown-menu megamenu">
<div class="row">
<div class="col-sm-6 col-lg-3">
<h5>America</h5>
<a class="dropdown-item" href="/usa/largest-companies-in-the-usa-by-market-cap/">🇺🇸 United States</a>
<a class="dropdown-item" href="/canada/largest-companies-in-canada-by-market-cap/">🇨🇦 Canada</a>
<a class="dropdown-item" href="/mexico/largest-companies-in-mexico-by-market-cap/">🇲🇽 Mexico</a>
<a class="dropdown-item" href="/brazil/largest-companies-in-brazil-by-market-cap/">🇧🇷 Brazil</a>
<a class="dropdown-item" href="/chile/largest-companies-in-chile-by-market-cap/">🇨🇱 Chile</a>
</div>
<div class="col-sm-6 col-lg-3 border-left">
<h5>Europe</h5>
<a class="dropdown-item" href="/european-union/largest-companies-in-the-eu-by-market-cap/">🇪🇺 European Union</a>
<a class="dropdown-item" href="/germany/largest-companies-in-germany-by-market-cap/">🇩🇪 Germany</a>
<a class="dropdown-item" href="/united-kingdom/largest-companies-in-the-uk-by-market-cap/">🇬🇧 United Kingdom</a>
<a class="dropdown-item" href="/france/largest-companies-in-france-by-market-cap/">🇫🇷 France</a>
<a class="dropdown-item" href="/spain/largest-companies-in-spain-by-market-cap/">🇪🇸 Spain</a>
<a class="dropdown-item" href="/netherlands/largest-companies-in-the-netherlands-by-market-cap/">🇳🇱 Netherlands</a>
<a class="dropdown-item" href="/sweden/largest-companies-in-sweden-by-market-cap/">🇸🇪 Sweden</a>
<a class="dropdown-item" href="/italy/largest-companies-in-italy-by-market-cap/">🇮🇹 Italy</a>
<a class="dropdown-item" href="/switzerland/largest-companies-in-switzerland-by-market-cap/">🇨🇭 Switzerland</a>
<a class="dropdown-item" href="/poland/largest-companies-in-poland-by-market-cap/">🇵🇱 Poland</a>
<a class="dropdown-item" href="/finland/largest-companies-in-finland-by-market-cap/">🇫🇮 Finland</a>
</div>
<div class="col-sm-6 col-lg-3 border-left">
<h5>Asia</h5>
<a class="dropdown-item" href="/china/largest-companies-in-china-by-market-cap/">🇨🇳 China</a>
<a class="dropdown-item" href="/japan/largest-companies-in-japan-by-market-cap/">🇯🇵 Japan</a>
<a class="dropdown-item" href="/south-korea/largest-companies-in-south-korea-by-market-cap/">🇰🇷 South Korea</a>
<a class="dropdown-item" href="/hong-kong/largest-companies-in-hong-kong-by-market-cap/">🇭🇰 Hong Kong</a>
<a class="dropdown-item" href="/singapore/largest-companies-in-singapore-by-market-cap/">🇸🇬 Singapore</a>
<a class="dropdown-item" href="/indonesia/largest-companies-in-indonesia-by-market-cap/">🇮🇩 Indonesia</a>
<a class="dropdown-item" href="/india/largest-companies-in-india-by-market-cap/">🇮🇳 India</a>
<a class="dropdown-item" href="/malaysia/largest-companies-in-malaysia-by-market-cap/">🇲🇾 Malaysia</a>
<a class="dropdown-item" href="/taiwan/largest-companies-in-taiwan-by-market-cap/">🇹🇼 Taiwan</a>
<a class="dropdown-item" href="/thailand/largest-companies-in-thailand-by-market-cap/">🇹🇭 Thailand</a>
<a class="dropdown-item" href="/vietnam/largest-companies-in-vietnam-by-market-cap/">🇻🇳 Vietnam</a>
</div>
<div class="col-sm-6 col-lg-3 border-left">
<h5>Others</h5>
<a class="dropdown-item" href="/australia/largest-companies-in-australia-by-market-cap/">🇦🇺 Australia</a>
<a class="dropdown-item" href="/new-zealand/largest-companies-in-new-zealand-by-market-cap/">🇳🇿 New Zealand</a>
<a class="dropdown-item" href="/israel/largest-companies-in-israel-by-market-cap/">🇮🇱 Israel</a>
<a class="dropdown-item" href="/saudi-arabia/largest-companies-in-saudi-arabia-by-market-cap/">🇸🇦 Saudi Arabia</a>
<a class="dropdown-item" href="/turkey/largest-companies-in-turkey-by-market-cap/">🇹🇷 Turkey</a>
<a class="dropdown-item" href="/russia/largest-companies-in-russia-by-market-cap/">🇷🇺 Russia</a>
<a class="dropdown-item" href="/south-africa/largest-companies-in-south-africa-by-market-cap/">🇿🇦 South Africa</a>
<a class="dropdown-item" href="/all-countries/"><strong>&gt;&gt; All Countries</strong></a>
</div>
</div>
</div>
</li>
<li class="nav-item dropdown megamenu-li">
<a aria-expanded="false" aria-haspopup="true" class="nav-link nav-link-companiesmarketcap dropdown-toggle" data-toggle="dropdown" href="#" id="dropdown-categories">Ranking by categories</a>
<div aria-labelledby="dropdown-categories" class="dropdown-menu megamenu">
<div class="row">
<div class="col-sm-6 col-lg-3">
<a class="dropdown-item" href="/assets-by-market-cap/">🏆 All assets by Market Cap</a>
<a class="dropdown-item" href="/automakers/largest-automakers-by-market-cap/">🚗 Automakers</a>
<a class="dropdown-item" href="/airlines/largest-airlines-by-market-cap/">✈️  Airlines</a>
<a class="dropdown-item" href="/airports/largest-airport-operating-companies-by-market-cap/">🛫 Airports</a>
<a class="dropdown-item" href="/aircraft-manufacturers/largest-aircraft-manufacturers-by-market-cap/">✈️  Aircraft manufacturers</a>
<a class="dropdown-item" href="/banks/largest-banks-by-market-cap/">🏦 Banks</a>
<a class="dropdown-item" href="/hotels/largest-hotel-companies-by-market-cap/">🏨 Hotels</a>
<a class="dropdown-item" href="/pharmaceuticals/largest-pharmaceutical-companies-by-market-cap/">💊 Pharmaceuticals</a>
<a class="dropdown-item" href="/e-commerce/largest-e-commerce-companies-by-market-cap/">🛒 E-Commerce</a>
<a class="dropdown-item" href="/healthcare/largest-healthcare-companies-by-market-cap/">⚕️ Healthcare</a>
</div>
<div class="col-sm-6 col-lg-3 border-left">
<a class="dropdown-item" href="/delivery-services/largest-delivery-companies-by-market-cap/">📦 Courier services</a>
<a class="dropdown-item" href="/media-press/largest-media-and-press-companies-by-market-cap/">📰 Media/Press</a>
<a class="dropdown-item" href="/alcoholic-beverages/largest-alcoholic-beverage-companies-by-market-cap/">🍷 Alcoholic beverages</a>
<a class="dropdown-item" href="/beverages/largest-beverage-companies-by-market-cap/">🥤 Beverages</a>
<a class="dropdown-item" href="/clothing/largest-clothing-companies-by-market-cap/">👚 Clothing</a>
<a class="dropdown-item" href="/mining/largest-mining-companies-by-market-cap/">⛏️ Mining</a>
<a class="dropdown-item" href="/railways/largest-railways-companies-by-market-cap/">🚂 Railways</a>
<a class="dropdown-item" href="/insurance/largest-insurance-companies-by-market-cap/">🏦 Insurance</a>
<a class="dropdown-item" href="/real-estate/largest-real-estate-companies-by-market-cap/">🏠 Real estate</a>
</div>
<div class="col-sm-6 col-lg-3 border-left">
<a class="dropdown-item" href="/ports/largest-port-operating-companies-by-market-cap/">⚓ Ports</a>
<a class="dropdown-item" href="/professional-services/largest-professional-service-companies-by-market-cap/">💼 Professional services</a>
<a class="dropdown-item" href="/food/largest-food-companies-by-market-cap/">🍴 Food</a>
<a class="dropdown-item" href="/restaurant-chains/largest-restaurant-chain-companies-by-market-cap/">🍔 Restaurant chains</a>
<a class="dropdown-item" href="/software/largest-software-companies-by-market-cap/">‍💻 Software</a>
<a class="dropdown-item" href="/semiconductors/largest-semiconductor-companies-by-market-cap/">📟 Semiconductors</a>
<a class="dropdown-item" href="/tobacco/largest-tobacco-companies-by-market-cap/"> 🚬 Tobacco</a>
<a class="dropdown-item" href="/financial-services/largest-financial-service-companies-by-market-cap/">💳 Financial services</a>
<a class="dropdown-item" href="/oil-gas/largest-oil-and-gas-companies-by-market-cap/">🛢 Oil&amp;Gas</a>
<a class="dropdown-item" href="/electricity/largest-electricity-companies-by-market-cap/">🔋 Electricity</a>
</div>
<div class="col-sm-6 col-lg-3 border-left">
<a class="dropdown-item" href="/chemicals/largest-chemical-companies-by-market-cap/">🧪 Chemicals</a>
<a class="dropdown-item" href="/investment/largest-investment-companies-by-market-cap/">💰 Investment</a>
<a class="dropdown-item" href="/telecommunication/largest-telecommunication-companies-by-market-cap/">📡 Telecommunication</a>
<a class="dropdown-item" href="/retail/largest-retail-companies-by-market-cap/">🛍️ Retail</a>
<a class="dropdown-item" href="/internet/largest-internet-companies-by-market-cap/">🖥️ Internet</a>
<a class="dropdown-item" href="/construction/largest-construction-companies-by-market-cap/">🏗 Construction</a>
<a class="dropdown-item" href="/video-games/largest-video-game-companies-by-market-cap/">🎮 Video Game</a>
<a class="dropdown-item" href="/tech/largest-tech-companies-by-market-cap/">💻 Tech</a>
<a class="dropdown-item" href="/artificial-intelligence/largest-ai-companies-by-marketcap/">🦾 AI</a>
<a class="dropdown-item" href="/all-categories/"><strong>&gt;&gt; All Categories</strong></a>
</div>
</div>
</div>
</li>
<li class="nav-item dropdown megamenu-li">
<a aria-expanded="false" aria-haspopup="true" class="nav-link nav-link-companiesmarketcap dropdown-toggle" data-toggle="dropdown" href="#" id="dropdown-categories">ETFs</a>
<div aria-labelledby="dropdown-categories" class="dropdown-menu megamenu">
<div class="row">
<div class="col-sm-6 col-lg-3">
<a class="dropdown-item" href="/etfs/largest-etfs-by-marketcap/">🏆 All ETFs</a>
<a class="dropdown-item" href="/bond-etfs/largest-bond-etfs-by-marketcap/">🏛️ Bond ETFs</a>
<a class="dropdown-item" href="/dividend-and-income-etfs/largest-dividend-etfs-by-marketcap/">％ Dividend ETFs</a>
<a class="dropdown-item" href="/bitcoin-etfs/largest-bitcoin-etfs-by-marketcap/">₿ Bitcoin ETFs</a>
<a class="dropdown-item" href="/ethereum-etfs/largest-ethereum-etfs-by-marketcap/">♢ Ethereum ETFs</a>

In [4]:
table = soup.find('table')

In [5]:
titles = table.find_all('th')

In [6]:
world_titles = [item.text for item in titles]

In [7]:
world_titles

['', 'Rank', 'Name', 'Revenue', 'Price', 'Today', 'Price (30 days)', 'Country']

In [8]:
df = pd.DataFrame(columns = world_titles)
df2 = pd.DataFrame(columns = world_titles)
df3 = pd.DataFrame(columns = world_titles)

In [9]:
df

Empty DataFrame
Columns: [, Rank, Name, Revenue, Price, Today, Price (30 days), Country]
Index: []

In [10]:
rows = table.find_all('tr')

In [11]:
for row in rows[1:18]:
    data = row.find_all('td')
    clean_data = [i.text.strip() for i in data]
    print(clean_data)
    length = len(df)
    df.loc[length] = clean_data

['', '1', 'WalmartWMT', '$703.06 B', '$133.89', '0.19%', '', '🇺🇸 USA']
['', '2', 'AmazonAMZN', '$691.33 B', '$198.79', '0.41%', '', '🇺🇸 USA']
['', '3', 'Saudi Aramco2222.SR', '$461.56 B', '$6.79', '0.47%', '', '🇸🇦 S. Arabia']
['', '4', 'Sinopec600028.SS', '$444.74 B', '$0.92', '3.48%', '', '🇨🇳 China']
['', '5', 'AppleAAPL', '$435.61 B', '$255.78', '2.27%', '', '🇺🇸 USA']
['', '6', 'UnitedHealthUNH', '$435.15 B', '$293.19', '3.10%', '', '🇺🇸 USA']
['', '7', 'McKessonMCK', '$397.95 B', '$934.75', '2.05%', '', '🇺🇸 USA']
['', '8', 'Berkshire Hathaway BRK-B', '$397.14 B', '$497.55', '0.49%', '', '🇺🇸 USA']
['', '9', 'PetroChina0857.HK', '$394.62 B', '$1.17', '1.44%', '', '🇨🇳 China']
['', '10', 'CVS HealthCVS', '$394.08 B', '$78.48', '0.71%', '', '🇺🇸 USA']
['', '11', 'Alphabet (Google)GOOG', '$385.47 B', '$306.02', '1.08%', '', '🇺🇸 USA']
['', '12', 'VolkswagenVOW3.DE', '$357.48 B', '$121.62', '0.39%', '', '🇩🇪 Germany']
['', '13', 'ToyotaTM', '$330.23 B', '$248.29', '2.75%', '', '🇯🇵 Japan']
['', '14', 'CencoraCOR', '$325.77 B', '$360.83', '2.96%', '', '🇺🇸 USA']
['', '15', 'Exxon MobilXOM', '$324.92 B', '$148.45', '0.99%', '', '🇺🇸 USA']
['', '16', 'MicrosoftMSFT', '$305.45 B', '$401.32', '0.13%', '', '🇺🇸 USA']
['', '17', 'China State Construction Engineering601668.SS', '$299.20 B', '$0.72', '0.79%', '', '🇨🇳 China']

In [12]:
df

,,Rank,Name,Revenue,Price,Today,Price (30 days),Country
0,,1,WalmartWMT,$703.06 B,$133.89,0.19%,,🇺🇸 USA
1,,2,AmazonAMZN,$691.33 B,$198.79,0.41%,,🇺🇸 USA
2,,3,Saudi Aramco2222.SR,$461.56 B,$6.79,0.47%,,🇸🇦 S. Arabia
3,,4,Sinopec600028.SS,$444.74 B,$0.92,3.48%,,🇨🇳 China
4,,5,AppleAAPL,$435.61 B,$255.78,2.27%,,🇺🇸 USA
5,,6,UnitedHealthUNH,$435.15 B,$293.19,3.10%,,🇺🇸 USA
6,,7,McKessonMCK,$397.95 B,$934.75,2.05%,,🇺🇸 USA
7,,8,Berkshire Hathaway BRK-B,$397.14 B,$497.55,0.49%,,🇺🇸 USA
8,,9,PetroChina0857.HK,$394.62 B,$1.17,1.44%,,🇨🇳 China
9,,10,CVS HealthCVS,$394.08 B,$78.48,0.71%,,🇺🇸 USA
10,,11,Alphabet (Google)GOOG,$385.47 B,$306.02,1.08%,,🇺🇸 USA
11,,12,VolkswagenVOW3.DE,$357.48 B,$121.62,0.39%,,🇩🇪 Germany
12,,13,ToyotaTM,$330.23 B,$248.29,2.75%,,🇯🇵 Japan
13,,14,CencoraCOR,$325.77 B,$360.83,2.96%,,🇺🇸 USA
14,,15,Exxon MobilXOM,$324.92 B,$148.45,0.99%,,🇺🇸 USA
15,,16,MicrosoftMSFT,$305.45 B,$401.32,0.13%,,🇺🇸 USA
16,,17,China State Construction Engineering601668.SS,$299.20 B,$0.72,0.79%,,🇨🇳 China

In [13]:
for row in rows[19:77]:
    data = row.find_all('td')
    clean_data2 = [i.text.strip() for i in data]
    print(clean_data2)
    length = len(df2)
    df2.loc[length] = clean_data2

['', '18', 'CostcoCOST', '$280.39 B', '$1,018', '1.96%', '', '🇺🇸 USA']
['', '19', 'ShellSHEL', '$269.07 B', '$78.77', '0.70%', '', '🇬🇧 UK']
['', '20', 'The Cigna GroupCI', '$267.93 B', '$291.44', '1.33%', '', '🇺🇸 USA']
['', '21', 'BullishBLSH', '$246.60 B', '$31.73', '0.06%', '', 'Cayman Islands']
['', '22', 'Foxconn (Hon Hai Precision Industry)2317.TW', '$243.54 B', '$7.23', '2.71%', '', '🇹🇼 Taiwan']
['', '23', 'Cardinal HealthCAH', '$234.31 B', '$220.79', '2.66%', '', '🇺🇸 USA']
['', '24', 'GlencoreGLCNF', '$230.94 B', '$6.65', '0.60%', '', '🇨🇭 Switzerland']
['', '25', 'Exor\r\nEXO.AS', '$223.05 B', '$83.43', '0.28%', '', '🇳🇱 Netherlands']
['', '26', 'Samsung005930.KS', '$222.04 B', '$125.43', '1.46%', '', '🇰🇷 S. Korea']
['', '27', 'Meta Platforms (Facebook)META', '$200.96 B', '$639.77', '1.55%', '', '🇺🇸 USA']
['', '28', 'Elevance HealthELV', '$194.82 B', '$346.80', '3.20%', '', '🇺🇸 USA']
['', '29', 'FordF', '$189.58 B', '$14.12', '1.95%', '', '🇺🇸 USA']
['', '30', 'BPBP', '$187.70 B', '$37.66', '1.26%', '', '🇬🇧 UK']
['', '31', 'NVIDIANVDA', '$187.14 B', '$182.78', '2.24%', '', '🇺🇸 USA']
['', '32', 'ChevronCVX', '$186.97 B', '$183.74', '0.73%', '', '🇺🇸 USA']
['', '33', 'CenteneCNC', '$185.85 B', '$40.58', '3.57%', '', '🇺🇸 USA']
['', '34', 'General MotorsGM', '$185.01 B', '$81.08', '1.44%', '', '🇺🇸 USA']
['', '35', 'TotalEnergiesTTE', '$183.53 B', '$76.79', '0.88%', '', '🇫🇷 France']
['', '36', 'JD.comJD', '$180.83 B', '$27.14', '1.38%', '', '🇨🇳 China']
['', '37', 'JPMorgan ChaseJPM', '$179.43 B', '$302.55', '0.03%', '', '🇺🇸 USA']
['', '38', 'Home DepotHD', '$166.18 B', '$391.05', '0.21%', '', '🇺🇸 USA']
['', '39', 'China Railway Group0390.HK', '$156.98 B', '$0.57', '0.67%', '', '🇨🇳 China']
['', '40', 'Mercedes-BenzMBG.DE', '$153.48 B', '$68.75', '0.69%', '', '🇩🇪 Germany']
['', '41', 'Allianz SEALV.DE', '$152.20 B', '$439.13', '0.43%', '', '🇩🇪 Germany']
['', '42', 'BMWBMW.DE', '$150.49 B', '$106.06', '0.09%', '', '🇩🇪 Germany']
['', '43', 'KrogerKR', '$147.22 B', '$71.25', '2.09%', '', '🇺🇸 USA']
['', '44', 'China Railway Construction\r\n601186.SS', '$144.65 B', '$1.04', '0.97%', '', '🇨🇳 China']
['', '45', 'HondaHMC', '$143.88 B', '$31.78', '1.11%', '', '🇯🇵 Japan']
['', '46', 'StoneX GroupSNEX', '$143.47 B', '$127.42', '1.98%', '', '🇺🇸 USA']
['', '47', 'China Mobile0941.HK', '$142.72 B', '$10.03', '0.26%', '', '🇨🇳 China']
['', '48', 'AlibabaBABA', '$140.34 B', '$155.73', '1.89%', '', '🇨🇳 China']
['', '49', 'VerizonVZ', '$137.49 B', '$49.01', '0.91%', '', '🇺🇸 USA']
['', '50', 'Ping An Insurance601318.SS', '$134.22 B', '$9.46', '1.88%', '', '🇨🇳 China']
['', '51', 'AXACS.PA', '$134.15 B', '$45.22', '1.19%', '', '🇫🇷 France']
['', '52', 'Mitsubishi Corporation8058.T', '$133.67 B', '$31.97', '0.77%', '', '🇯🇵 Japan']
['', '53', 'Marathon PetroleumMPC', '$133.26 B', '$203.26', '2.65%', '', '🇺🇸 USA']
['', '54', 'Phillips 66PSX', '$131.95 B', '$159.77', '2.25%', '', '🇺🇸 USA']
['', '55', 'Deutsche TelekomDTE.DE', '$131.33 B', '$39.39', '0.88%', '', '🇩🇪 Germany']
['', '56', 'Hyundai005380.KS', '$131.04 B', '$345.43', '1.38%', '', '🇰🇷 S. Korea']
['', '57', 'CITIC limited0267.HK', '$130.12 B', '$1.58', '1.14%', '', '🇨🇳 China']
['', '58', 'PrudentialPUK', '$128.74 B', '$29.53', '0.84%', '', '🇬🇧 UK']
['', '59', 'HumanaHUM', '$126.36 B', '$184.10', '2.95%', '', '🇺🇸 USA']
['', '60', 'AT&TT', '$124.48 B', '$28.69', '0.38%', '', '🇺🇸 USA']
['', '61', 'ComcastCMCSA', '$123.70 B', '$31.57', '0.79%', '', '🇺🇸 USA']
['', '62', 'Valero EnergyVLO', '$123.07 B', '$200.17', '1.66%', '', '🇺🇸 USA']
['', '63', 'BYD002594.SZ', '$117.84 B', '$13.08', '0.98%', '', '🇨🇳 China']
['', '64', 'Reliance IndustriesRELIANCE.NS', '$116.49 B', '$15.68', '0.95%', '', '🇮🇳 India']
['', '65', 'ICBC1398.HK', '$114.64 B', '$0.82', '0.16%', '', '🇨🇳 China']
['', '66', 'Bank of America BAC', '$107.26 B', '$52.55', '0.06%', '', '🇺🇸 USA']
['', '67', 'EquinorEQNR', '$107.06 B', '$28.10', '1.77%', '', '🇳🇴 Norway']
['', '68', 'Life Insurance Corporation of India (LIC)LICI.NS', '$106.16 B', '$9.64', '0.72%', '', '🇮🇳 India']
['', '69', 'China Construction Bank601939.SS', '$105.59 B', '$1.26', '1.25%', '', '🇨🇳 China']
['', '70', 'TargetTGT', '$105.24 B', '$115.76', '2.72%', '', '🇺🇸 USA']
['', '71', 'China Communications Construction601800.SS', '$104.15 B', '$1.16', '0.62%', '', '🇨🇳 China']
['', '72', 'DellDELL', '$104.09 B', '$117.49', '4.14%', '', '🇺🇸 USA']
['', '73', 'Ahold DelhaizeAD.AS', '$103.02 B', '$47.24', '0.76%', '', '🇳🇱 Netherlands']
['', '74', 'NestléNESN.SW', '$101.54 B', '$104.67', '0.42%', '', '🇨🇭 Switzerland']
['', '75', 'StellantisSTLA', '$101.26 B', '$7.75', '1.90%', '', '🇳🇱 Netherlands']

In [14]:
df2

,,Rank,Name,Revenue,Price,Today,Price (30 days),Country
0,,18,CostcoCOST,$280.39 B,"$1,018",1.96%,,🇺🇸 USA
1,,19,ShellSHEL,$269.07 B,$78.77,0.70%,,🇬🇧 UK
2,,20,The Cigna GroupCI,$267.93 B,$291.44,1.33%,,🇺🇸 USA
3,,21,BullishBLSH,$246.60 B,$31.73,0.06%,,Cayman Islands
4,,22,Foxconn (Hon Hai Precision Industry)2317.TW,$243.54 B,$7.23,2.71%,,🇹🇼 Taiwan
5,,23,Cardinal HealthCAH,$234.31 B,$220.79,2.66%,,🇺🇸 USA
6,,24,GlencoreGLCNF,$230.94 B,$6.65,0.60%,,🇨🇭 Switzerland
7,,25,Exor\r\nEXO.AS,$223.05 B,$83.43,0.28%,,🇳🇱 Netherlands
8,,26,Samsung005930.KS,$222.04 B,$125.43,1.46%,,🇰🇷 S. Korea
9,,27,Meta Platforms (Facebook)META,$200.96 B,$639.77,1.55%,,🇺🇸 USA
10,,28,Elevance HealthELV,$194.82 B,$346.80,3.20%,,🇺🇸 USA
11,,29,FordF,$189.58 B,$14.12,1.95%,,🇺🇸 USA
12,,30,BPBP,$187.70 B,$37.66,1.26%,,🇬🇧 UK
13,,31,NVIDIANVDA,$187.14 B,$182.78,2.24%,,🇺🇸 USA
14,,32,ChevronCVX,$186.97 B,$183.74,0.73%,,🇺🇸 USA
15,,33,CenteneCNC,$185.85 B,$40.58,3.57%,,🇺🇸 USA
16,,34,General MotorsGM,$185.01 B,$81.08,1.44%,,🇺🇸 USA
17,,35,TotalEnergiesTTE,$183.53 B,$76.79,0.88%,,🇫🇷 France
18,,36,JD.comJD,$180.83 B,$27.14,1.38%,,🇨🇳 China
19,,37,JPMorgan ChaseJPM,$179.43 B,$302.55,0.03%,,🇺🇸 USA
20,,38,Home DepotHD,$166.18 B,$391.05,0.21%,,🇺🇸 USA
21,,39,China Railway Group0390.HK,$156.98 B,$0.57,0.67%,,🇨🇳 China
22,,40,Mercedes-BenzMBG.DE,$153.48 B,$68.75,0.69%,,🇩🇪 Germany
23,,41,Allianz SEALV.DE,$152.20 B,$439.13,0.43%,,🇩🇪 Germany
24,,42,BMWBMW.DE,$150.49 B,$106.06,0.09%,,🇩🇪 Germany
25,,43,KrogerKR,$147.22 B,$71.25,2.09%,,🇺🇸 USA
26,,44,China Railway Construction\r\n601186.SS,$144.65 B,$1.04,0.97%,,🇨🇳 China
27,,45,HondaHMC,$143.88 B,$31.78,1.11%,,🇯🇵 Japan
28,,46,StoneX GroupSNEX,$143.47 B,$127.42,1.98%,,🇺🇸 USA
29,,47,China Mobile0941.HK,$142.72 B,$10.03,0.26%,,🇨🇳 China
30,,48,AlibabaBABA,$140.34 B,$155.73,1.89%,,🇨🇳 China
31,,49,VerizonVZ,$137.49 B,$49.01,0.91%,,🇺🇸 USA
32,,50,Ping An Insurance601318.SS,$134.22 B,$9.46,1.88%,,🇨🇳 China
33,,51,AXACS.PA,$134.15 B,$45.22,1.19%,,🇫🇷 France
34,,52,Mitsubishi Corporation8058.T,$133.67 B,$31.97,0.77%,,🇯🇵 Japan
35,,53,Marathon PetroleumMPC,$133.26 B,$203.26,2.65%,,🇺🇸 USA
36,,54,Phillips 66PSX,$131.95 B,$159.77,2.25%,,🇺🇸 USA
37,,55,Deutsche TelekomDTE.DE,$131.33 B,$39.39,0.88%,,🇩🇪 Germany
38,,56,Hyundai005380.KS,$131.04 B,$345.43,1.38%,,🇰🇷 S. Korea
39,,57,CITIC limited0267.HK,$130.12 B,$1.58,1.14%,,🇨🇳 China
40,,58,PrudentialPUK,$128.74 B,$29.53,0.84%,,🇬🇧 UK
41,,59,HumanaHUM,$126.36 B,$184.10,2.95%,,🇺🇸 USA
42,,60,AT&TT,$124.48 B,$28.69,0.38%,,🇺🇸 USA
43,,61,ComcastCMCSA,$123.70 B,$31.57,0.79%,,🇺🇸 USA
44,,62,Valero EnergyVLO,$123.07 B,$200.17,1.66%,,🇺🇸 USA
45,,63,BYD002594.SZ,$117.84 B,$13.08,0.98%,,🇨🇳 China
46,,64,Reliance IndustriesRELIANCE.NS,$116.49 B,$15.68,0.95%,,🇮🇳 India
47,,65,ICBC1398.HK,$114.64 B,$0.82,0.16%,,🇨🇳 China
48,,66,Bank of America BAC,$107.26 B,$52.55,0.06%,,🇺🇸 USA
49,,67,EquinorEQNR,$107.06 B,$28.10,1.77%,,🇳🇴 Norway
50,,68,Life Insurance Corporation of India (LIC)LICI.NS,$106.16 B,$9.64,0.72%,,🇮🇳 India
51,,69,China Construction Bank601939.SS,$105.59 B,$1.26,1.25%,,🇨🇳 China
52,,70,TargetTGT,$105.24 B,$115.76,2.72%,,🇺🇸 USA
53,,71,China Communications Construction601800.SS,$104.15 B,$1.16,0.62%,,🇨🇳 China
54,,72,DellDELL,$104.09 B,$117.49,4.14%,,🇺🇸 USA
55,,73,Ahold DelhaizeAD.AS,$103.02 B,$47.24,0.76%,,🇳🇱 Netherlands
56,,74,NestléNESN.SW,$101.54 B,$104.67,0.42%,,🇨🇭 Switzerland
57,,75,StellantisSTLA,$101.26 B,$7.75,1.90%,,🇳🇱 Netherlands

In [15]:
for row in rows[78:]:
    data = row.find_all('td')
    clean_data3 = [i.text.strip() for i in data]
    print(clean_data3)
    length = len(df3)
    df3.loc[length] = clean_data3

['', '76', 'Agricultural Bank of China601288.SS', '$99.97 B', '$0.94', '1.51%', '', '🇨🇳 China']
['', '77', 'Foxconn Industrial Internet\r\n601138.SS', '$98.01 B', '$7.93', '1.05%', '', '🇨🇳 China']
['', '78', 'Itōchū Shōji8001.T', '$95.82 B', '$14.06', '0.28%', '', '🇯🇵 Japan']
['', '79', 'Walt DisneyDIS', '$95.71 B', '$105.45', '3.00%', '', '🇺🇸 USA']
['', '80', 'LVMHMC.PA', '$94.92 B', '$622.81', '1.47%', '', '🇫🇷 France']
['', '81', 'TeslaTSLA', '$94.82 B', '$417.44', '0.09%', '', '🇺🇸 USA']
['', '82', 'ENIE', '$94.68 B', '$43.45', '1.33%', '', '🇮🇹 Italy']
['', '83', 'ENEOS Holdings5020.T', '$94.60 B', '$9.29', '1.54%', '', '🇯🇵 Japan']
['', '84', 'PepsicoPEP', '$93.92 B', '$165.94', '0.75%', '', '🇺🇸 USA']
['', '85', 'DHL Group (Deutsche Post)DHL.DE', '$92.44 B', '$57.92', '0.02%', '', '🇩🇪 Germany']
['', '86', 'Johnson & JohnsonJNJ', '$92.14 B', '$243.45', '0.45%', '', '🇺🇸 USA']
['', '87', 'NTT (Nippon Telegraph & Telephone)\r\n\r\n9432.T', '$91.24 B', '$1.00', '0.71%', '', '🇯🇵 Japan']
['', '88', 'Mitsui Bussan\r\n8031.T', '$91.05 B', '$35.50', '3.05%', '', '🇯🇵 Japan']
['', '89', 'CarrefourCA.PA', '$90.81 B', '$18.40', '0.16%', '', '🇫🇷 France']
['', '90', 'TencentTCEHY', '$90.11 B', '$68.30', '1.38%', '', '🇨🇳 China']
['', '91', 'FedExFDX', '$90.09 B', '$374.72', '1.42%', '', '🇺🇸 USA']
['', '92', 'E.ONEOAN.DE', '$90.07 B', '$22.20', '0.40%', '', '🇩🇪 Germany']
['', '93', 'United Parcel ServiceUPS', '$89.48 B', '$119.24', '0.99%', '', '🇺🇸 USA']
['', '94', 'BoeingBA', '$89.46 B', '$242.96', '1.51%', '', '🇺🇸 USA']
['', '95', 'SAIC Motor\r\n600104.SS', '$89.35 B', '$2.07', '0.56%', '', '🇨🇳 China']
['', '96', 'Power Construction Corporation of China601669.SS', '$89.26 B', '$0.79', '1.63%', '', '🇨🇳 China']
['', '97', 'Bank of China601988.SS', '$89.08 B', '$0.77', '0.56%', '', '🇨🇳 China']
['', '98', 'VinciDG.PA', '$88.92 B', '$161.83', '0.00%', '', '🇫🇷 France']
['', '99', 'SiemensSIE.DE', '$88.45 B', '$276.41', '0.66%', '', '🇩🇪 Germany']
['', '100', 'Indian OilIOC.NS', '$88.36 B', '$1.92', '0.35%', '', '🇮🇳 India']

In [16]:
df3

,,Rank,Name,Revenue,Price,Today,Price (30 days),Country
0,,76,Agricultural Bank of China601288.SS,$99.97 B,$0.94,1.51%,,🇨🇳 China
1,,77,Foxconn Industrial Internet\r\n601138.SS,$98.01 B,$7.93,1.05%,,🇨🇳 China
2,,78,Itōchū Shōji8001.T,$95.82 B,$14.06,0.28%,,🇯🇵 Japan
3,,79,Walt DisneyDIS,$95.71 B,$105.45,3.00%,,🇺🇸 USA
4,,80,LVMHMC.PA,$94.92 B,$622.81,1.47%,,🇫🇷 France
5,,81,TeslaTSLA,$94.82 B,$417.44,0.09%,,🇺🇸 USA
6,,82,ENIE,$94.68 B,$43.45,1.33%,,🇮🇹 Italy
7,,83,ENEOS Holdings5020.T,$94.60 B,$9.29,1.54%,,🇯🇵 Japan
8,,84,PepsicoPEP,$93.92 B,$165.94,0.75%,,🇺🇸 USA
9,,85,DHL Group (Deutsche Post)DHL.DE,$92.44 B,$57.92,0.02%,,🇩🇪 Germany
10,,86,Johnson & JohnsonJNJ,$92.14 B,$243.45,0.45%,,🇺🇸 USA
11,,87,NTT (Nippon Telegraph & Telephone)\r\n\r\n9432.T,$91.24 B,$1.00,0.71%,,🇯🇵 Japan
12,,88,Mitsui Bussan\r\n8031.T,$91.05 B,$35.50,3.05%,,🇯🇵 Japan
13,,89,CarrefourCA.PA,$90.81 B,$18.40,0.16%,,🇫🇷 France
14,,90,TencentTCEHY,$90.11 B,$68.30,1.38%,,🇨🇳 China
15,,91,FedExFDX,$90.09 B,$374.72,1.42%,,🇺🇸 USA
16,,92,E.ONEOAN.DE,$90.07 B,$22.20,0.40%,,🇩🇪 Germany
17,,93,United Parcel ServiceUPS,$89.48 B,$119.24,0.99%,,🇺🇸 USA
18,,94,BoeingBA,$89.46 B,$242.96,1.51%,,🇺🇸 USA
19,,95,SAIC Motor\r\n600104.SS,$89.35 B,$2.07,0.56%,,🇨🇳 China
20,,96,Power Construction Corporation of China601669.SS,$89.26 B,$0.79,1.63%,,🇨🇳 China
21,,97,Bank of China601988.SS,$89.08 B,$0.77,0.56%,,🇨🇳 China
22,,98,VinciDG.PA,$88.92 B,$161.83,0.00%,,🇫🇷 France
23,,99,SiemensSIE.DE,$88.45 B,$276.41,0.66%,,🇩🇪 Germany
24,,100,Indian OilIOC.NS,$88.36 B,$1.92,0.35%,,🇮🇳 India

In [20]:
final_df = pd.concat([df, df2, df3])

In [18]:
pd.set_option('display.max.rows', 101)

In [23]:
final_df = final_df.set_index('Rank')

KeyError: "None of ['Rank'] are in the columns"

In [24]:
final_df

,,Name,Revenue,Price,Today,Price (30 days),Country
Rank,,,,,,,
1,,WalmartWMT,$703.06 B,$133.89,0.19%,,🇺🇸 USA
2,,AmazonAMZN,$691.33 B,$198.79,0.41%,,🇺🇸 USA
3,,Saudi Aramco2222.SR,$461.56 B,$6.79,0.47%,,🇸🇦 S. Arabia
4,,Sinopec600028.SS,$444.74 B,$0.92,3.48%,,🇨🇳 China
5,,AppleAAPL,$435.61 B,$255.78,2.27%,,🇺🇸 USA
6,,UnitedHealthUNH,$435.15 B,$293.19,3.10%,,🇺🇸 USA
7,,McKessonMCK,$397.95 B,$934.75,2.05%,,🇺🇸 USA
8,,Berkshire Hathaway BRK-B,$397.14 B,$497.55,0.49%,,🇺🇸 USA
9,,PetroChina0857.HK,$394.62 B,$1.17,1.44%,,🇨🇳 China
10,,CVS HealthCVS,$394.08 B,$78.48,0.71%,,🇺🇸 USA
11,,Alphabet (Google)GOOG,$385.47 B,$306.02,1.08%,,🇺🇸 USA
12,,VolkswagenVOW3.DE,$357.48 B,$121.62,0.39%,,🇩🇪 Germany
13,,ToyotaTM,$330.23 B,$248.29,2.75%,,🇯🇵 Japan
14,,CencoraCOR,$325.77 B,$360.83,2.96%,,🇺🇸 USA
15,,Exxon MobilXOM,$324.92 B,$148.45,0.99%,,🇺🇸 USA
16,,MicrosoftMSFT,$305.45 B,$401.32,0.13%,,🇺🇸 USA
17,,China State Construction Engineering601668.SS,$299.20 B,$0.72,0.79%,,🇨🇳 China
18,,CostcoCOST,$280.39 B,"$1,018",1.96%,,🇺🇸 USA
19,,ShellSHEL,$269.07 B,$78.77,0.70%,,🇬🇧 UK
20,,The Cigna GroupCI,$267.93 B,$291.44,1.33%,,🇺🇸 USA
21,,BullishBLSH,$246.60 B,$31.73,0.06%,,Cayman Islands
22,,Foxconn (Hon Hai Precision Industry)2317.TW,$243.54 B,$7.23,2.71%,,🇹🇼 Taiwan
23,,Cardinal HealthCAH,$234.31 B,$220.79,2.66%,,🇺🇸 USA
24,,GlencoreGLCNF,$230.94 B,$6.65,0.60%,,🇨🇭 Switzerland
25,,Exor\r\nEXO.AS,$223.05 B,$83.43,0.28%,,🇳🇱 Netherlands
26,,Samsung005930.KS,$222.04 B,$125.43,1.46%,,🇰🇷 S. Korea
27,,Meta Platforms (Facebook)META,$200.96 B,$639.77,1.55%,,🇺🇸 USA
28,,Elevance HealthELV,$194.82 B,$346.80,3.20%,,🇺🇸 USA
29,,FordF,$189.58 B,$14.12,1.95%,,🇺🇸 USA
30,,BPBP,$187.70 B,$37.66,1.26%,,🇬🇧 UK
31,,NVIDIANVDA,$187.14 B,$182.78,2.24%,,🇺🇸 USA
32,,ChevronCVX,$186.97 B,$183.74,0.73%,,🇺🇸 USA
33,,CenteneCNC,$185.85 B,$40.58,3.57%,,🇺🇸 USA
34,,General MotorsGM,$185.01 B,$81.08,1.44%,,🇺🇸 USA
35,,TotalEnergiesTTE,$183.53 B,$76.79,0.88%,,🇫🇷 France
36,,JD.comJD,$180.83 B,$27.14,1.38%,,🇨🇳 China
37,,JPMorgan ChaseJPM,$179.43 B,$302.55,0.03%,,🇺🇸 USA
38,,Home DepotHD,$166.18 B,$391.05,0.21%,,🇺🇸 USA
39,,China Railway Group0390.HK,$156.98 B,$0.57,0.67%,,🇨🇳 China
40,,Mercedes-BenzMBG.DE,$153.48 B,$68.75,0.69%,,🇩🇪 Germany
41,,Allianz SEALV.DE,$152.20 B,$439.13,0.43%,,🇩🇪 Germany
42,,BMWBMW.DE,$150.49 B,$106.06,0.09%,,🇩🇪 Germany
43,,KrogerKR,$147.22 B,$71.25,2.09%,,🇺🇸 USA
44,,China Railway Construction\r\n601186.SS,$144.65 B,$1.04,0.97%,,🇨🇳 China
45,,HondaHMC,$143.88 B,$31.78,1.11%,,🇯🇵 Japan
46,,StoneX GroupSNEX,$143.47 B,$127.42,1.98%,,🇺🇸 USA
47,,China Mobile0941.HK,$142.72 B,$10.03,0.26%,,🇨🇳 China
48,,AlibabaBABA,$140.34 B,$155.73,1.89%,,🇨🇳 China
49,,VerizonVZ,$137.49 B,$49.01,0.91%,,🇺🇸 USA
50,,Ping An Insurance601318.SS,$134.22 B,$9.46,1.88%,,🇨🇳 China
51,,AXACS.PA,$134.15 B,$45.22,1.19%,,🇫🇷 France
52,,Mitsubishi Corporation8058.T,$133.67 B,$31.97,0.77%,,🇯🇵 Japan
53,,Marathon PetroleumMPC,$133.26 B,$203.26,2.65%,,🇺🇸 USA
54,,Phillips 66PSX,$131.95 B,$159.77,2.25%,,🇺🇸 USA
55,,Deutsche TelekomDTE.DE,$131.33 B,$39.39,0.88%,,🇩🇪 Germany
56,,Hyundai005380.KS,$131.04 B,$345.43,1.38%,,🇰🇷 S. Korea
57,,CITIC limited0267.HK,$130.12 B,$1.58,1.14%,,🇨🇳 China
58,,PrudentialPUK,$128.74 B,$29.53,0.84%,,🇬🇧 UK
59,,HumanaHUM,$126.36 B,$184.10,2.95%,,🇺🇸 USA
60,,AT&TT,$124.48 B,$28.69,0.38%,,🇺🇸 USA
61,,ComcastCMCSA,$123.70 B,$31.57,0.79%,,🇺🇸 USA
62,,Valero EnergyVLO,$123.07 B,$200.17,1.66%,,🇺🇸 USA
63,,BYD002594.SZ,$117.84 B,$13.08,0.98%,,🇨🇳 China
64,,Reliance IndustriesRELIANCE.NS,$116.49 B,$15.68,0.95%,,🇮🇳 India
65,,ICBC1398.HK,$114.64 B,$0.82,0.16%,,🇨🇳 China
66,,Bank of America BAC,$107.26 B,$52.55,0.06%,,🇺🇸 USA
67,,EquinorEQNR,$107.06 B,$28.10,1.77%,,🇳🇴 Norway
68,,Life Insurance Corporation of India (LIC)LICI.NS,$106.16 B,$9.64,0.72%,,🇮🇳 India
69,,China Construction Bank601939.SS,$105.59 B,$1.26,1.25%,,🇨🇳 China
70,,TargetTGT,$105.24 B,$115.76,2.72%,,🇺🇸 USA
71,,China Communications Construction601800.SS,$104.15 B,$1.16,0.62%,,🇨🇳 China
72,,DellDELL,$104.09 B,$117.49,4.14%,,🇺🇸 USA
73,,Ahold DelhaizeAD.AS,$103.02 B,$47.24,0.76%,,🇳🇱 Netherlands
74,,NestléNESN.SW,$101.54 B,$104.67,0.42%,,🇨🇭 Switzerland
75,,StellantisSTLA,$101.26 B,$7.75,1.90%,,🇳🇱 Netherlands
76,,Agricultural Bank of China601288.SS,$99.97 B,$0.94,1.51%,,🇨🇳 China
77,,Foxconn Industrial Internet\r\n601138.SS,$98.01 B,$7.93,1.05%,,🇨🇳 China
78,,Itōchū Shōji8001.T,$95.82 B,$14.06,0.28%,,🇯🇵 Japan
79,,Walt DisneyDIS,$95.71 B,$105.45,3.00%,,🇺🇸 USA
80,,LVMHMC.PA,$94.92 B,$622.81,1.47%,,🇫🇷 France
81,,TeslaTSLA,$94.82 B,$417.44,0.09%,,🇺🇸 USA
82,,ENIE,$94.68 B,$43.45,1.33%,,🇮🇹 Italy
83,,ENEOS Holdings5020.T,$94.60 B,$9.29,1.54%,,🇯🇵 Japan
84,,PepsicoPEP,$93.92 B,$165.94,0.75%,,🇺🇸 USA
85,,DHL Group (Deutsche Post)DHL.DE,$92.44 B,$57.92,0.02%,,🇩🇪 Germany
86,,Johnson & JohnsonJNJ,$92.14 B,$243.45,0.45%,,🇺🇸 USA
87,,NTT (Nippon Telegraph & Telephone)\r\n\r\n9432.T,$91.24 B,$1.00,0.71%,,🇯🇵 Japan
88,,Mitsui Bussan\r\n8031.T,$91.05 B,$35.50,3.05%,,🇯🇵 Japan
89,,CarrefourCA.PA,$90.81 B,$18.40,0.16%,,🇫🇷 France
90,,TencentTCEHY,$90.11 B,$68.30,1.38%,,🇨🇳 China
91,,FedExFDX,$90.09 B,$374.72,1.42%,,🇺🇸 USA
92,,E.ONEOAN.DE,$90.07 B,$22.20,0.40%,,🇩🇪 Germany
93,,United Parcel ServiceUPS,$89.48 B,$119.24,0.99%,,🇺🇸 USA
94,,BoeingBA,$89.46 B,$242.96,1.51%,,🇺🇸 USA
95,,SAIC Motor\r\n600104.SS,$89.35 B,$2.07,0.56%,,🇨🇳 China
96,,Power Construction Corporation of China601669.SS,$89.26 B,$0.79,1.63%,,🇨🇳 China
97,,Bank of China601988.SS,$89.08 B,$0.77,0.56%,,🇨🇳 China
98,,VinciDG.PA,$88.92 B,$161.83,0.00%,,🇫🇷 France
99,,SiemensSIE.DE,$88.45 B,$276.41,0.66%,,🇩🇪 Germany
100,,Indian OilIOC.NS,$88.36 B,$1.92,0.35%,,🇮🇳 India

In [25]:
final_df.to_csv(r'C:\Users\amyud\Downloads\top 100 companies.csv')